# Generated by Django 5.1.1 on 2024-10-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body_element',
            name='body_img',
            field=models.ImageField(blank=True, null=True, upload_to='body_img'),
        ),
        migrations.AlterField(
            model_name='headset_element',
            name='headset_img',
            field=models.ImageField(blank=True, null=True, upload_to='headset_img/'),
        ),
    ]
