# Generated by Django 5.1.1 on 2024-10-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0002_alter_body_element_body_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincomp',
            name='adahan',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
