# Generated by Django 5.1.1 on 2024-10-17 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0004_alter_showcomp_body_category_alter_showcomp_cooling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compchoices',
            name='procecor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.processor_element', verbose_name='процессор'),
        ),
    ]
