# Generated by Django 5.1.1 on 2024-10-17 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0005_alter_compchoices_procecor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='body_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.body_category', verbose_name='корпус'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cooling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.cooling_category', verbose_name='охлождения'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='dvd_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.dvd_drive_category', verbose_name='DVD привод'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='hard_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.hard_drive_category', verbose_name='жесткий диск'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='headset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.headset_category', verbose_name='гарнитура'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='keyboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.keyboard_category', verbose_name='клавиатура'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='manitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.manitor_category', verbose_name='манитор'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.random_access_memory_category', verbose_name='оперативнная памят'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='motherboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.the_motherboard_category', verbose_name='Материнская плата'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='mouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.mouse_catergory', verbose_name='мышь'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.operating_system_category', verbose_name='Операционнвя система'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='power_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.power_unit_category', verbose_name='блок питания'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='procecor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.processor_element', verbose_name='процессор'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sound_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.sound_card_category', verbose_name='звуковая карта'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ssd_drive_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.ssd_drive_1_category', verbose_name='SSD диск 1'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ssd_drive_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.ssd_drive_2_category', verbose_name='SSD диск 2'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='video_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.video_card_category', verbose_name='видео карта'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='wi_fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.wi_fi_category', verbose_name='wi-fi'),
        ),
    ]
