# Generated by Django 5.1.1 on 2024-10-17 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0006_cartitem_body_category_cartitem_cooling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='procecor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_site.processor_category', verbose_name='процессор'),
        ),
    ]
