# Generated by Django 5.1.1 on 2024-11-01 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0007_alter_cartitem_procecor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcomp',
            name='dvd_drive',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='dvd_drive',
        ),
        migrations.RemoveField(
            model_name='compchoices',
            name='dvd_drive',
        ),
        migrations.RemoveField(
            model_name='dvd_drive_element',
            name='middle_dvd_drive_conaction',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='body_category',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cooling',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='hard_drive',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='headset',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='keyboard',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='manitor',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='motherboard',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='mouse',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='power_unit',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='procecor',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='sound_card',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='ssd_drive_1',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='ssd_drive_2',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='video_card',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='wi_fi',
        ),
        migrations.DeleteModel(
            name='DVD_drive_category',
        ),
        migrations.DeleteModel(
            name='DVD_drive_element',
        ),
    ]
